adding RP emulator
echopen/PRJ-medtec_androidapp pull request #44
Opened 2017-06-06 12:39 UTC by jerome2echopen

2017-06-07 07:53 UTC, clecoued requested changes
folder name should be renamed from RedPitaya_emulator to Probe_emulator

2017-06-07 08:05 UTC, clecoued commented on RedPitaya_emulator/srcbin/stepper.h
> +#ifndef STEPPER_H
the stepper file is not needed in probe_emulator

2017-06-07 08:05 UTC, clecoued commented on RedPitaya_emulator/srcbin/emul.c
> +	load(buffer_length, Nline, data0, "hand.txt");
it would be nice to support a serie of images

2017-06-07 08:10 UTC, clecoued commented on RedPitaya_emulator/srcbin/emul.c
> +float x0=80.0;
I think we should define and read a config file for probe settings associated with each images

2017-06-07 09:20 UTC, clecoued commented
update run.sh to launch executable from linux/mac laptop or red pitaya

2017-06-08 15:44 UTC, jerome2echopen commented
Need to make the bash file now

2017-06-08 19:16 UTC, kelu124 commented on RedPitaya_emulator/srcbin/emul.c
> +float x0=80.0;
And ideally list some settings as well - that could be used as well in the long run to identify the settings / variables / configs / ... that will need to be stored in a dicom.

2017-06-14 08:28 UTC, clecoued approved these changes

2017-06-14 08:31 UTC, merged